### ISSUE TITLE
invalid java requirements

### ISSUE THREAD

**Issue by DO1JLR** [alvistack/ansible-role-fisheye#4]
Hi

In the requirements you install the openjdk 11 on debian buster -> https://github.com/alvistack/ansible-role-fisheye/blob/master/ansible-galaxy-requirements.yml#L31L33

```bash
$ /opt/atlassian/fisheye/bin/start.sh -fg
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
$ java --version
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Debian-3deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Debian-3deb10u1, mixed mode, sharing)
```
Unfortunately fisheye does not seem to get along with this.

**Comment by DO1JLR** [comment]
it looks like openjdk-8 is working for fisheye...

**Comment by hswong3i** [comment]
I am waiting JDK 11 support by Fisheye since long long long ago :-(

See https://confluence.atlassian.com/fisheye/supported-platforms-960155252.html

**Comment by DO1JLR** [comment]
> I am waiting JDK 11 support by Fisheye since long long long ago :-(
> 
> See https://confluence.atlassian.com/fisheye/supported-platforms-960155252.html

Yes, I hope they will update it soon. But this did not solve the issue that it is currently not working with openjdk 11!

Or what do you think @hswong3i ? Just ignor it? maybe you want to write something about that to the README?

**Comment by hswong3i** [comment]
Ok i just pinning `openjdk_release: "8"` for standard per-OS based Molecule test cases, but forget to handle it for `molecule converge -s default`, fixed by https://github.com/alvistack/ansible-role-fisheye/commit/a84ea4da013f1c2563565d3bccc4da1b2b3b41ca

**Comment by DO1JLR** [comment]
thanks <3

stay healthy
