### ISSUE TITLE
Feature Request. External Database

### ISSUE THREAD

**Issue by DO1JLR** [alvistack/ansible-role-fisheye#5]
Hello

It would be mega cool if you could use an external postgres database for fisheye optionally.

stay healthy

**Comment by hswong3i** [comment]
Please provide more detail? How you like it be happened?

By default database connection is configured AFTER initial archive extract + service start + web UI accessible from browser. It is not handled by this role, and have no plan to be handled within this role.

**Comment by DO1JLR** [comment]
Well, you're right.
I can't actually find a configuration file where you can "just for now" define the database. It seems to be the easiest way to do it through the webUI.

Please excuse the interruption.
